apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  namespace: default
  labels:
    app: hasura
    hasuraService: custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hasura
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
      annotations:
        scriptExecutedAt: 'dummyvalue'
    spec:
      volumes:
        - name: secret-vol
          secret:
            secretName: jpmc-secret
      containers:
        - image: hasura/graphql-engine:v2.7.0
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:postgrespassword@10.100.140.14:5432/postgres
            ## enable the console served by server
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: 'true'
            ## enable debugging mode. It is recommended to disable this in production
            - name: HASURA_GRAPHQL_DEV_MODE
              value: 'true'
            - name: JWT_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jpmc-secret
                  key: token
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: secret-vol
              mountPath: '/etc/jpmc_secret'
          resources: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: default
  labels:
    name: secret-pod
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: jpmc-secret
  containers:
    - name: secret-refresh-pod
      image: secret-refresh-pod
      imagePullPolicy: Never
      volumeMounts:
        - name: secret-vol
          mountPath: '/etc/jpmc_secret'
