apiVersion: v1
kind: Service
metadata:
  name: hasura
  namespace: default
  labels:
    app: hasura
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: hasura
