apiVersion: v1 
kind: Pod 
metadata:
  name: secret-pod 
  labels: 
    name: secert-pod
    app: hasura 
spec: 
  volumes:
  - name: secret-vol
    secret:
      secretName: jpmc-secret
  containers:
    - name: secret-refresh-pod
      image: secret-refresh-pod
      imagePullPolicy: Never
      volumeMounts:
        - name: secret-vol
          mountPath: "/etc/jpmc_secret"
