apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      volumes:
      - name: secret-vol 
        secret:
          secretName: jpmc-secret
      containers:
      - image: hasura/graphql-engine:v2.7.0
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://postgres:postgrespassword@10.109.5.48:5432/postgres
        ## enable the console served by server
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ## enable debugging mode. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"
        volumeMounts:
        - name: secret-vol
          mountPath: "/etc/jpmc_secret"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}